### PR TITLE
Ldbruce patch 2

### PR DESCRIPTION
**Pull request by ldbruce-2018**

### CODE REVIEW

**Comment by ldbruce-2018** [comment]
merge commits

**Review by ldbruce-2018 — COMMENTED** [review]
approve changes

**Comment by chfritz** [comment]
Hi Liana,

The changes you are proposing here are for the demo repository itself, not your own fork (copy) of it. Please fork the repository and then apply your changes to your fork, where you won't need my approval to merge them. Let me know if you need any help with that. If you are interested in an easier way of creating a webpage with bibbase, you can also try one of our premium plans, which include a hosted website with an easy to use editor and where embedding publication lists is trivial.

Best,
Christian

**Comment by ldbruce-2018** [comment]
Hi Christian,

My apologies, that was created in error.

Best,
-Liana

**Pull request closed without merging**
